# Generated by Django 5.2.4 on 2025-08-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.category",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="project_name",
            field=models.CharField(default="Unnamed Project", max_length=255),
            preserve_default=False,
        ),
    ]
