# Generated by Django 5.2.4 on 2025-08-17 18:59

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_category_customuser_project_name"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="district",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="region",
                chained_model_field="region",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.district",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="common.region",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                    ("seller", "Sotuvchi"),
                ],
                default="seller",
                max_length=20,
            ),
        ),
    ]
