# Generated by Django 5.2.4 on 2025-08-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_district_customuser_region_and_more"),
        ("store", "0003_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.address"
            ),
        ),
    ]
