# Generated by Django 5.2.4 on 2025-08-20 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_ad_status_ad_view_count_alter_category_icon_adimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_ads", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
