# Generated by Django 5.2.4 on 2025-08-20 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_favouriteproduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favouriteproduct",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="favouriteproduct",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="favouriteproduct",
            unique_together={("user", "product", "device_id")},
        ),
    ]
