# Generated by Django 5.2.4 on 2025-08-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_favouriteproduct_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="likes",
        ),
    ]
