# Generated by Django 5.2.4 on 2025-08-21 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_searchcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.category",
            ),
        ),
    ]
