# Generated by Django 5.2.4 on 2025-08-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_searchhistory_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="price_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="price_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
