# Generated by Django 5.2.4 on 2025-08-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("store", "0014_searchhistory_price_max_searchhistory_price_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="region_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_searches",
                to="common.region",
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_searches",
                to="store.category",
            ),
        ),
    ]
