# Generated by Django 5.2.4 on 2025-08-09 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("title_uz", models.CharField(max_length=250, null=True)),
                ("title_ru", models.CharField(max_length=250, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", models.TextField()),
                ("content_uz", models.TextField(null=True)),
                ("content_ru", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_uz", models.CharField(max_length=100, null=True, unique=True)),
                ("name_ru", models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=20)),
                ("support_email", models.EmailField(max_length=254)),
                ("working_hours", models.CharField(max_length=100)),
                ("working_hours_uz", models.CharField(max_length=100, null=True)),
                ("working_hours_ru", models.CharField(max_length=100, null=True)),
                ("app_version", models.CharField(max_length=50)),
                ("maintenance_mode", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("name_uz", models.CharField(max_length=100, null=True)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="common.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("region", "name")},
            },
        ),
    ]
