# Generated by Django 5.2.4 on 2025-08-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_uz',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
