# Generated by Django 5.2.4 on 2025-08-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_page_slug_ru_page_slug_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug_uz',
        ),
    ]
