# Generated by Django 5.2.4 on 2025-08-06 10:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_region_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="district",
            name="guid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="region",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="guid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="guid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
