# Generated by Django 5.2.4 on 2025-08-07 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_district_guid_alter_page_guid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=20)),
                ("support_email", models.EmailField(max_length=254)),
                ("working_hours", models.CharField(max_length=100)),
                ("app_version", models.CharField(max_length=50)),
                ("maintenance_mode", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
