# Generated by Django 5.2.4 on 2025-08-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="working_hours_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="working_hours_uz",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
